apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "distllm.fullname" . }}-config
  labels:
    {{- include "distllm.labels" . | nindent 4 }}
data:
  distllm.yaml: |
    coordinator:
      host: {{ .Values.env.DISTLLM_COORDINATOR_HOST }}
    log_level: {{ .Values.env.DISTLLM_LOG_LEVEL }}
    {{- if .Values.redis.enabled }}
    redis:
      address: "{{ .Values.redis.address | default (printf "%s-redis:6379" (include "distllm.fullname" .)) }}"
      {{- if .Values.redis.password }}
      password: "{{ .Values.redis.password }}"
      {{- end }}
    {{- end }}
