{{- if .Values.redis.enabled }}
{{- if .Values.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "distllm.fullname" . }}-redis
  labels:
    {{- include "distllm.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: "{{ .Values.redis.password }}"
{{- end }}
{{- end }}
