apiVersion: v1
kind: Service
metadata:
  name: {{ include "distllm.fullname" . }}
  labels:
    {{- include "distllm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.rest.port }}
      targetPort: http
      name: http
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      name: grpc
    - port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "distllm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
