apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-

commonLabels:
  environment: staging
  app.kubernetes.io/environment: staging

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: coordinator
    path: coordinator-patch.yaml
  - target:
      kind: Deployment
      name: worker
    path: coordinator-patch.yaml
  - target:
      kind: HorizontalPodAutoscaler
      name: coordinator
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2
      - op: replace
        path: /spec/maxReplicas
        value: 6
  - target:
      kind: HorizontalPodAutoscaler
      name: worker
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2
      - op: replace
        path: /spec/maxReplicas
        value: 6
  - target:
      kind: ConfigMap
      name: config
    patch: |-
      - op: replace
        path: /data/distllm.yaml
        value: |
          coordinator:
            host: "0.0.0.0"
          log_level: info
          redis:
            address: "staging-distllm-redis:6379"

replicas:
  - name: coordinator
    count: 2
  - name: worker
    count: 2
