{{- if and .Values.podDisruptionBudget.coordinator.enabled (gt (int .Values.coordinator.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "distllm.fullname" . }}-coordinator
  labels:
    {{- include "distllm.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.coordinator.minAvailable }}
  selector:
    matchLabels:
      {{- include "distllm.coordinatorLabels" . | nindent 6 }}
{{- end }}
