{{- if .Values.podDisruptionBudget.worker.enabled }}
{{- range $pool := .Values.nodePools }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "distllm.fullname" $ }}-worker-{{ $pool.name }}
  labels:
    {{- include "distllm.labels" $ | nindent 4 }}
    {{- include "distllm.workerLabels" (dict "root" $ "pool" $pool) | nindent 4 }}
spec:
  minAvailable: {{ $.Values.podDisruptionBudget.worker.minAvailable }}
  selector:
    matchLabels:
      {{- include "distllm.workerLabels" (dict "root" $ "pool" $pool) | nindent 6 }}
{{- end }}
{{- end }}
