{{- if .Values.persistence.cache.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "distllm.fullname" . }}-cache
  labels:
    {{- include "distllm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.cache.size }}
  {{- if .Values.persistence.cache.storageClass }}
  storageClassName: {{ .Values.persistence.cache.storageClass }}
  {{- end }}
---
{{- end }}
{{- if .Values.persistence.audit.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "distllm.fullname" . }}-audit
  labels:
    {{- include "distllm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.audit.size }}
  {{- if .Values.persistence.audit.storageClass }}
  storageClassName: {{ .Values.persistence.audit.storageClass }}
  {{- end }}
{{- end }}
