apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  labels:
    app.kubernetes.io/component: coordinator
data:
  distllm.yaml: |
    coordinator:
      host: "0.0.0.0"
    log_level: info
    redis:
      address: "distllm-redis:6379"
