"""CLI command group for profile presets.

Commands:
    list    — table all 7 presets with name, description, and key features
    show    — display a preset's full config as formatted YAML
    apply   — generate a config.yaml file from a preset
"""

from __future__ import annotations

from typing import Any

import typer
from rich.console import Console
from rich.table import Table

from distllm.config.profiles import ProfileConfig

profile_app = typer.Typer(help="Profile presets: list, show, apply")
console = Console()


def _preset_features(preset: dict[str, Any]) -> str:
    """Derive a compact feature summary from a preset config dict."""
    keys = [k for k in preset if k != "description"]
    if not keys:
        return ""
    parts: list[str] = []
    for k in sorted(keys):
        v = preset[k]
        if isinstance(v, dict):
            # Flatten one level: "batching: max_batch_size=8"
            inner = ",".join(f"{ik}={iv}" for ik, iv in v.items())
            parts.append(f"{k}: {inner}")
        else:
            parts.append(f"{k}={v}")
    return " | ".join(parts)


@profile_app.command("list")
def profile_list() -> None:
    """List all available configuration presets."""
    presets = ProfileConfig.list_presets()  # {name: description}

    # Enrich with key features from the raw _PRESETS data
    table = Table(title="Configuration Presets")
    table.add_column("Name", style="cyan", no_wrap=True)
    table.add_column("Description", style="green")
    table.add_column("Key Features", style="dim")

    for name in sorted(presets):
        desc = presets[name]
        full = ProfileConfig.get_preset(name) or {}
        features = _preset_features(full)
        table.add_row(name, desc, features)

    console.print(table)


@profile_app.command("show")
def profile_show(
    name: str = typer.Argument(..., help="Preset name to display"),
) -> None:
    """Show the full configuration of a preset as formatted YAML."""
    preset = ProfileConfig.get_preset(name)
    if preset is None:
        supported = ", ".join(sorted(ProfileConfig.SUPPORTED_PRESETS))
        console.print(f"[red]Unknown preset:[/red] {name}")
        console.print(f"  Supported presets: {supported}")
        raise typer.Exit(1)

    import yaml

    # Omit the description key — this is a config dump
    config = {k: v for k, v in preset.items() if k != "description"}
    output = yaml.dump(
        {name: config},
        default_flow_style=False,
        sort_keys=False,
        indent=2,
        allow_unicode=True,
    )
    console.print(output[:-1])  # strip trailing newline for clean display


@profile_app.command("apply")
def profile_apply(
    name: str = typer.Argument(..., help="Preset name to apply"),
    output: str = typer.Option(
        "config.yaml",
        "--output",
        "-o",
        help="Output config file path",
    ),
) -> None:
    """Generate a config.yaml file from a preset."""
    preset = ProfileConfig.get_preset(name)
    if preset is None:
        supported = ", ".join(sorted(ProfileConfig.SUPPORTED_PRESETS))
        console.print(f"[red]Unknown preset:[/red] {name}")
        console.print(f"  Supported presets: {supported}")
        raise typer.Exit(1)

    import yaml

    description = preset.get("description", "")
    config = {k: v for k, v in preset.items() if k != "description"}

    header = (
        f"# Configuration generated from preset: {name}\n"
        f"# {description}\n"
        "#\n"
        f"# Generated by: distllm config profile apply {name}\n"
    )

    yaml_content = yaml.dump(
        config,
        default_flow_style=False,
        sort_keys=False,
        indent=2,
        allow_unicode=True,
    )

    with open(output, "w", encoding="utf-8") as f:
        f.write(header)
        f.write(yaml_content)

    console.print(f"[green]Config written to {output}[/green]")
    console.print(f"[dim]Preset: {name} — {description}[/dim]")
