# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import node_pb2 as proto_dot_node__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/node_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeServiceStub(object):
    """Node service - each worker node implements this
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ForwardPass = channel.unary_unary(
                '/distributed_llm.NodeService/ForwardPass',
                request_serializer=proto_dot_node__pb2.ForwardPassRequest.SerializeToString,
                response_deserializer=proto_dot_node__pb2.ForwardPassResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/distributed_llm.NodeService/HealthCheck',
                request_serializer=proto_dot_node__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=proto_dot_node__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetNodeInfo = channel.unary_unary(
                '/distributed_llm.NodeService/GetNodeInfo',
                request_serializer=proto_dot_node__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=proto_dot_node__pb2.NodeInfo.FromString,
                _registered_method=True)
        self.GossipExchange = channel.unary_unary(
                '/distributed_llm.NodeService/GossipExchange',
                request_serializer=proto_dot_node__pb2.GossipAdvertisement.SerializeToString,
                response_deserializer=proto_dot_node__pb2.GossipAdvertisement.FromString,
                _registered_method=True)
        self.RequestCache = channel.unary_unary(
                '/distributed_llm.NodeService/RequestCache',
                request_serializer=proto_dot_node__pb2.GossipRequest.SerializeToString,
                response_deserializer=proto_dot_node__pb2.GossipResponse.FromString,
                _registered_method=True)
        self.MoEForward = channel.unary_unary(
                '/distributed_llm.NodeService/MoEForward',
                request_serializer=proto_dot_node__pb2.MoEForwardRequest.SerializeToString,
                response_deserializer=proto_dot_node__pb2.MoEForwardResponse.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """Node service - each worker node implements this
    """

    def ForwardPass(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GossipExchange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoEForward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ForwardPass': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardPass,
                    request_deserializer=proto_dot_node__pb2.ForwardPassRequest.FromString,
                    response_serializer=proto_dot_node__pb2.ForwardPassResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_node__pb2.HealthCheckRequest.FromString,
                    response_serializer=proto_dot_node__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetNodeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeInfo,
                    request_deserializer=proto_dot_node__pb2.HealthCheckRequest.FromString,
                    response_serializer=proto_dot_node__pb2.NodeInfo.SerializeToString,
            ),
            'GossipExchange': grpc.unary_unary_rpc_method_handler(
                    servicer.GossipExchange,
                    request_deserializer=proto_dot_node__pb2.GossipAdvertisement.FromString,
                    response_serializer=proto_dot_node__pb2.GossipAdvertisement.SerializeToString,
            ),
            'RequestCache': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestCache,
                    request_deserializer=proto_dot_node__pb2.GossipRequest.FromString,
                    response_serializer=proto_dot_node__pb2.GossipResponse.SerializeToString,
            ),
            'MoEForward': grpc.unary_unary_rpc_method_handler(
                    servicer.MoEForward,
                    request_deserializer=proto_dot_node__pb2.MoEForwardRequest.FromString,
                    response_serializer=proto_dot_node__pb2.MoEForwardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_llm.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_llm.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """Node service - each worker node implements this
    """

    @staticmethod
    def ForwardPass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_llm.NodeService/ForwardPass',
            proto_dot_node__pb2.ForwardPassRequest.SerializeToString,
            proto_dot_node__pb2.ForwardPassResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_llm.NodeService/HealthCheck',
            proto_dot_node__pb2.HealthCheckRequest.SerializeToString,
            proto_dot_node__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_llm.NodeService/GetNodeInfo',
            proto_dot_node__pb2.HealthCheckRequest.SerializeToString,
            proto_dot_node__pb2.NodeInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GossipExchange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_llm.NodeService/GossipExchange',
            proto_dot_node__pb2.GossipAdvertisement.SerializeToString,
            proto_dot_node__pb2.GossipAdvertisement.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_llm.NodeService/RequestCache',
            proto_dot_node__pb2.GossipRequest.SerializeToString,
            proto_dot_node__pb2.GossipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoEForward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_llm.NodeService/MoEForward',
            proto_dot_node__pb2.MoEForwardRequest.SerializeToString,
            proto_dot_node__pb2.MoEForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoordinatorServiceStub(object):
    """Coordinator service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/distributed_llm.CoordinatorService/RegisterNode',
                request_serializer=proto_dot_node__pb2.NodeRegistration.SerializeToString,
                response_deserializer=proto_dot_node__pb2.RegistrationResponse.FromString,
                _registered_method=True)
        self.Infer = channel.unary_unary(
                '/distributed_llm.CoordinatorService/Infer',
                request_serializer=proto_dot_node__pb2.InferenceRequest.SerializeToString,
                response_deserializer=proto_dot_node__pb2.LogitsResponse.FromString,
                _registered_method=True)
        self.StreamInfer = channel.unary_stream(
                '/distributed_llm.CoordinatorService/StreamInfer',
                request_serializer=proto_dot_node__pb2.InferenceRequest.SerializeToString,
                response_deserializer=proto_dot_node__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/distributed_llm.CoordinatorService/ListModels',
                request_serializer=proto_dot_node__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=proto_dot_node__pb2.ModelListResponse.FromString,
                _registered_method=True)


class CoordinatorServiceServicer(object):
    """Coordinator service
    """

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Infer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamInfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=proto_dot_node__pb2.NodeRegistration.FromString,
                    response_serializer=proto_dot_node__pb2.RegistrationResponse.SerializeToString,
            ),
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=proto_dot_node__pb2.InferenceRequest.FromString,
                    response_serializer=proto_dot_node__pb2.LogitsResponse.SerializeToString,
            ),
            'StreamInfer': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamInfer,
                    request_deserializer=proto_dot_node__pb2.InferenceRequest.FromString,
                    response_serializer=proto_dot_node__pb2.TokenResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=proto_dot_node__pb2.HealthCheckRequest.FromString,
                    response_serializer=proto_dot_node__pb2.ModelListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_llm.CoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_llm.CoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorService(object):
    """Coordinator service
    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_llm.CoordinatorService/RegisterNode',
            proto_dot_node__pb2.NodeRegistration.SerializeToString,
            proto_dot_node__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_llm.CoordinatorService/Infer',
            proto_dot_node__pb2.InferenceRequest.SerializeToString,
            proto_dot_node__pb2.LogitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamInfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/distributed_llm.CoordinatorService/StreamInfer',
            proto_dot_node__pb2.InferenceRequest.SerializeToString,
            proto_dot_node__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_llm.CoordinatorService/ListModels',
            proto_dot_node__pb2.HealthCheckRequest.SerializeToString,
            proto_dot_node__pb2.ModelListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
