"""Weights & Biases integration for experiment tracking.

Merged class combining the full API surface of both original implementations:

* :class:`WandBIntegration` from ``integrations/wandb_tracking.py`` (GPU
  monitoring, latency histograms, model artefacts, explicit lifecycle)
* :class:`WandbExperiment` from ``distllm.dist.wandb_integration`` (partition
  plans, quantisation results, external run injection, ``watch_model``)

Usage::

    from distllm_wandb import WandBIntegration

    tracker = WandBIntegration(
        project="distllm-experiment",
        config={"learning_rate": 1e-4, "batch_size": 32},
    )
    with tracker:
        for step in range(100):
            tracker.log_metrics({"loss": 0.05, "accuracy": 0.97}, step=step)

        tracker.log_model(my_model, "transformer-v1")
        tracker.log_partition_plan(partition_solution)
"""

from __future__ import annotations

import atexit
import logging
import os
import tempfile
import threading
import time
from typing import Any

logger = logging.getLogger("distllm")

try:
    import wandb

    _WANDB_AVAILABLE = True
except ImportError:
    _WANDB_AVAILABLE = False

# ---------------------------------------------------------------------------
# GPU monitoring (best-effort via nvidia-ml-py / pynvml) — lazy init
# ---------------------------------------------------------------------------

_NVM_AVAILABLE = False
_NVM_INITIALISED = False
_nvm_lock = threading.Lock()


def _ensure_nvml() -> bool:
    """Lazily initialise pynvml on the first GPU poll.

    Returns ``True`` if pynvml is available and initialised.
    """
    global _NVM_AVAILABLE, _NVM_INITIALISED  # noqa: PLW0603
    if _NVM_INITIALISED:
        return _NVM_AVAILABLE
    with _nvm_lock:
        if _NVM_INITIALISED:
            return _NVM_AVAILABLE
        _NVM_INITIALISED = True
        try:
            import pynvml  # type: ignore[import-untyped]

            pynvml.nvmlInit()
            _NVM_AVAILABLE = True
        except (ImportError, RuntimeError, OSError):
            pass
    return _NVM_AVAILABLE


def _sample_gpu_usage() -> dict[str, Any]:
    """Return per-device GPU utilisation metrics.

    Returns a dict keyed by device index (e.g. ``"gpu_0_util_pct"``,
    ``"gpu_0_mem_pct"``, ``"gpu_0_temp_c"``).  Returns an empty dict when
    pynvml is unavailable or initialisation failed.
    """
    if not _ensure_nvml():
        return {}
    try:
        import pynvml  # type: ignore[import-untyped]

        device_count = pynvml.nvmlDeviceGetCount()
        metrics: dict[str, Any] = {}
        for i in range(device_count):
            handle = pynvml.nvmlDeviceGetHandleByIndex(i)
            util = pynvml.nvmlDeviceGetUtilizationRates(handle)
            mem_info = pynvml.nvmlDeviceGetMemoryInfo(handle)
            temperature = pynvml.nvmlDeviceGetTemperature(
                handle, pynvml.NVML_TEMPERATURE_GPU
            )
            metrics[f"gpu_{i}_util_pct"] = util.gpu
            metrics[f"gpu_{i}_mem_pct"] = (
                (mem_info.used / mem_info.total) * 100 if mem_info.total > 0 else 0.0
            )
            metrics[f"gpu_{i}_temp_c"] = float(temperature)
        return metrics
    except Exception:
        logger.debug("Failed to sample GPU usage", exc_info=True)
        return {}


# ---------------------------------------------------------------------------
# WandBIntegration  (merged)
# ---------------------------------------------------------------------------


class WandBIntegration:
    """Weights & Biases experiment tracker for distributed-LLM (merged).

    Parameters
    ----------
    project:
        W&B project name.  Runs are grouped by project on the W&B dashboard.
    config:
        Optional hyper-parameter / configuration dictionary attached to the
        run for filtering and comparison on the dashboard.
    entity:
        W&B team or username.  If ``None`` the default entity for the
        logged-in user is used.
    run_name:
        Optional human-readable name for this run.  Auto-generated by W&B
        when omitted.
    tags:
        Optional list of tags for dashboard filtering.
    group:
        Optional group name — runs sharing the same group appear side-by-side
        on the W&B dashboard.
    watch_model:
        If ``True``, call ``wandb.watch`` on models passed to
        :meth:`log_model` (gradient histograms, topology).
    log_gpu:
        If ``True``, poll GPU usage in a background thread every
        *gpu_poll_interval* seconds.
    gpu_poll_interval:
        Seconds between GPU utilisation samples (must be > 0, default 10).
    run:
        An externally-managed ``wandb.Run`` (or anything duck-typed like it).
        When provided the constructor will **not** call ``wandb.init`` and
        ``__exit__`` will **not** call ``run.finish()``.

    Raises
    ------
    ValueError
        If *gpu_poll_interval* is not positive.
    """

    def __init__(
        self,
        project: str = "distllm",
        config: dict[str, Any] | None = None,
        entity: str | None = None,
        run_name: str | None = None,
        tags: list[str] | None = None,
        group: str | None = None,
        watch_model: bool = False,
        log_gpu: bool = True,
        gpu_poll_interval: float = 10.0,
        run: Any = None,
    ) -> None:
        if gpu_poll_interval <= 0:
            raise ValueError(
                f"gpu_poll_interval must be > 0, got {gpu_poll_interval}"
            )

        self.project = project
        self.config = config or {}
        self.entity = entity
        self.run_name = run_name
        self.tags = tags
        self.group = group
        self._watch_model_enabled = watch_model
        self.log_gpu = log_gpu
        self.gpu_poll_interval = gpu_poll_interval

        # External run injection
        self._external_run = run is not None
        self._run: Any = run
        self._started = False
        self._finished = False
        self._step = 0
        self._gpu_thread: threading.Thread | None = None
        self._gpu_stop_event = threading.Event()
        self._latency_buffer: list[float] = []
        self._latency_buffer_lock = threading.RLock()
        self._warning_emitted = False

        if not _WANDB_AVAILABLE:
            logger.info("wandb not installed — WandBIntegration is a no-op")

    # -- lifecycle ---------------------------------------------------------

    def start(self) -> None:
        """Initialise the W&B run and start background monitors.

        Called automatically on entering a ``with`` block.  Safe to call
        multiple times — subsequent calls are no-ops.

        When an external *run* was passed to the constructor, ``start()``
        uses that run directly without calling ``wandb.init``.
        """
        if self._started or self._finished:
            return
        if not _WANDB_AVAILABLE:
            self._emit_warning()
            self._started = True
            return

        try:
            if self._external_run:
                # Use the externally-provided run directly
                self._started = True
                logger.debug("W&B run attached from external source")
            else:
                self._run = wandb.init(
                    project=self.project,
                    config=self.config,
                    entity=self.entity,
                    name=self.run_name,
                    tags=self.tags,
                    group=self.group,
                    reinit=True,
                )
                self._started = True
                logger.info(
                    "W&B run started: %s/%s  (url: %s)",
                    self.project,
                    self._run.name or self.run_name,
                    self._run.get_url() if hasattr(self._run, "get_url") else "N/A",
                )

            # Background GPU monitor
            if self.log_gpu:
                self._start_gpu_monitor()

            # Ensure finish() is called on interpreter exit
            atexit.register(self.finish)

        except Exception as exc:
            logger.warning("Failed to initialise W&B run: %s", exc)
            self._started = True  # prevent retry

    def finish(self) -> None:
        """Flush pending metrics and finish the W&B run.

        Safe to call multiple times — subsequent calls are no-ops.
        Does **not** call ``run.finish()`` for externally-injected runs.
        """
        if self._finished:
            return

        # Flush any accumulated latency histograms before closing.
        self._flush_latency_buffer()

        self._stop_gpu_monitor()

        if _WANDB_AVAILABLE and self._run is not None and not self._external_run:
            try:
                self._run.finish()
                logger.debug("W&B run finished")
            except Exception as exc:
                logger.warning("Failed to finish W&B run: %s", exc)

        self._finished = True
        self._started = False
        self._run = None
        atexit.unregister(self.finish)

    def __enter__(self) -> WandBIntegration:
        self.start()
        return self

    def __exit__(self, *args: Any) -> None:
        self.finish()

    # -- metric logging ---------------------------------------------------

    def log_metrics(
        self,
        metrics: dict[str, float],
        step: int | None = None,
    ) -> None:
        """Log scalar metrics to the current W&B run.

        Parameters
        ----------
        metrics:
            Dictionary of metric names to scalar values.
        step:
            Global step number.  Auto-incremented when omitted.
        """
        step = step if step is not None else self._step

        if self._ensure_ready():
            try:
                self._run.log(metrics, step=step)  # type: ignore[union-attr]
            except Exception as exc:
                logger.warning("Failed to log metrics to W&B: %s", exc)

        self._step = max(self._step, step + 1) if step is not None else step + 1

    def log_latencies(
        self,
        latencies: list[float],
        step: int | None = None,
    ) -> None:
        """Log latency distribution percentiles (p50, p95, p99).

        Parameters
        ----------
        latencies:
            List of latency values in milliseconds.
        step:
            Optional step number.  When omitted the value is appended to an
            internal buffer that is flushed every 100 calls or on
            :meth:`finish`, so that percentile calculations are more stable.
        """
        if not latencies:
            return

        if step is not None:
            self._log_latency_summary(latencies, step)
            return

        # Buffer for batched flush
        with self._latency_buffer_lock:
            self._latency_buffer.extend(latencies)
            if len(self._latency_buffer) >= 100:
                self._flush_latency_buffer()

    def _log_latency_summary(
        self,
        latencies: list[float],
        step: int,
    ) -> None:
        """Compute and log latency percentiles immediately."""
        if not _WANDB_AVAILABLE or self._run is None:
            return
        sorted_lat = sorted(latencies)
        n = len(sorted_lat)
        if n == 0:
            return
        summary = {
            "latency_p50_ms": sorted_lat[n // 2],
            "latency_p95_ms": sorted_lat[int(n * 0.95)],
            "latency_p99_ms": sorted_lat[int(n * 0.99)],
            "latency_min_ms": sorted_lat[0],
            "latency_max_ms": sorted_lat[-1],
            "latency_avg_ms": sum(sorted_lat) / n,
            "latency_count": n,
        }
        try:
            self._run.log(summary, step=step)
        except Exception as exc:
            logger.warning("Failed to log latency summary: %s", exc)

    def _flush_latency_buffer(self) -> None:
        """Flush the internal latency buffer as a single summary log entry."""
        with self._latency_buffer_lock:
            if not self._latency_buffer:
                return
            buf = self._latency_buffer
            self._latency_buffer = []
        self._log_latency_summary(buf, self._step)

    # -- partition plan logging -------------------------------------------

    def log_partition_plan(self, plan: Any) -> None:
        """Log a partition plan as a W&B Table.

        Parameters
        ----------
        plan:
            A ``PartitionSolution`` or similar object with
            ``node_assignments`` and ``throughput_estimate``.
        """
        if not self._ensure_ready():
            return
        try:
            columns = [
                "node_id", "start_layer", "end_layer",
                "compute_ms", "memory_gb",
            ]
            data: list[list[Any]] = []

            assignments = (
                getattr(plan, "node_assignments", None)
                or getattr(plan, "assignments", [])
            )
            for assignment in assignments:
                if isinstance(assignment, dict):
                    data.append([
                        assignment.get("node_id", ""),
                        assignment.get("start_layer", 0),
                        assignment.get("end_layer", 0),
                        round(assignment.get("compute_ms", 0), 1),
                        round(assignment.get("memory_gb", 0), 1),
                    ])
                elif hasattr(assignment, "node_id"):
                    data.append([
                        assignment.node_id,
                        getattr(assignment, "start_layer", 0),
                        getattr(assignment, "end_layer", 0),
                        round(getattr(assignment, "compute_ms", 0), 1),
                        round(getattr(assignment, "memory_gb", 0), 1),
                    ])

            if data:
                table = wandb.Table(columns=columns, data=data)
                self._run.log({"partition_plan": table})

            throughput = (
                getattr(plan, "throughput_estimate", None)
                or getattr(plan, "throughput", None)
            )
            if throughput is not None:
                self._run.log({"throughput_tokens_per_sec": throughput})
        except Exception as exc:
            logger.warning("Failed to log partition plan to W&B: %s", exc)

    # -- quantisation results logging ------------------------------------

    def log_quant_results(self, results: Any) -> None:
        """Log quantization tuning results.

        Parameters
        ----------
        results:
            Dict or list of per-layer quantization results
            with ``layer_name``, ``method``, ``accuracy``, ``speedup``.
        """
        if not self._ensure_ready():
            return
        try:
            if isinstance(results, dict):
                results = [results]
            if isinstance(results, list):
                columns = ["layer", "method", "accuracy", "speedup"]
                data = []
                for r in results:
                    if isinstance(r, dict):
                        data.append([
                            r.get("layer", r.get("layer_name", "")),
                            r.get("method", ""),
                            r.get("accuracy", r.get("perplexity", 0)),
                            r.get("speedup", r.get("throughput_gain", 0)),
                        ])
                if data:
                    table = wandb.Table(columns=columns, data=data)
                    self._run.log({"quantization_results": table})

            total_accuracy = 0
            count = 0
            for r in (results if isinstance(results, list) else [results]):
                acc = (
                    r.get("accuracy")
                    if isinstance(r, dict)
                    else getattr(r, "accuracy", None)
                )
                if acc is not None:
                    total_accuracy += acc
                    count += 1
            if count > 0:
                self._run.log({"avg_accuracy": total_accuracy / count})
        except Exception as exc:
            logger.warning("Failed to log quant results to W&B: %s", exc)

    # -- artifact logging -------------------------------------------------

    def log_artifacts(
        self, local_path: str, artifact_type: str = "model"
    ) -> None:
        """Log a local file or directory as a W&B artifact.

        Parameters
        ----------
        local_path:
            Filesystem path to the file or directory to upload.
        artifact_type:
            W&B artifact type (default ``"model"``).
        """
        if not self._ensure_ready():
            return
        try:
            artifact = wandb.Artifact(
                name=f"{self.project}-{int(time.time())}",
                type=artifact_type,
            )
            if os.path.isfile(local_path):
                artifact.add_file(local_path)
            elif os.path.isdir(local_path):
                artifact.add_dir(local_path)
            self._run.log_artifact(artifact)
        except Exception as exc:
            logger.warning("Failed to log artifact to W&B: %s", exc)

    # -- model logging ----------------------------------------------------

    def log_model(self, model: Any, name: str) -> None:
        """Log a model to W&B.

        When ``watch_model`` was set on construction and ``wandb.watch`` is
        available, the model is registered for gradient/topology tracking.

        The model is also saved as a W&B artifact so that it can be compared
        across runs on the dashboard.

        Parameters
        ----------
        model:
            PyTorch ``nn.Module`` or other model object.  If it has a
            ``state_dict`` method it will be serialised via ``torch.save``;
            otherwise the ``__dict__`` is logged as run config.
        name:
            Human-readable name for the model version in W&B artifacts.
        """
        if not self._ensure_ready():
            return

        # Gradient / topology watching
        if self._watch_model_enabled and _WANDB_AVAILABLE:
            try:
                wandb.watch(model, log="all", log_freq=100)
            except Exception as exc:
                logger.warning("Failed to watch model: %s", exc)

        # Serialise and upload as an artifact
        try:
            artifact = wandb.Artifact(name=name, type="model")

            # Prefer PyTorch serialisation when torch and state_dict are present
            if hasattr(model, "state_dict"):
                self._save_torch_model(model, artifact)
            else:
                artifact.add_reference(name)

            self._run.log_artifact(artifact)  # type: ignore[union-attr]
            logger.info("Logged model artifact: %s", name)

        except Exception as exc:
            logger.warning("Failed to log model to W&B: %s", exc)

    @staticmethod
    def _save_torch_model(model: Any, artifact: Any) -> None:
        """Attempt to save a PyTorch model via ``torch.save``."""
        try:
            import torch

            tmp_dir = tempfile.gettempdir()
            tmp_path = os.path.join(tmp_dir, f"wandb_model_{int(time.time())}.pt")
            torch.save(model.state_dict(), tmp_path)
            artifact.add_file(tmp_path)
            # Clean-up local file
            try:
                os.remove(tmp_path)
            except OSError:
                pass
        except ImportError:
            # torch not available — fall through silently
            pass
        except Exception:
            logger.debug("Failed to serialise model with torch.save", exc_info=True)

    # -- model watching (explicit) ---------------------------------------

    def watch_model(self, model: Any, log_freq: int = 100) -> None:
        """Watch a PyTorch model's gradients and topology.

        This is an explicit call to ``wandb.watch``, independent of the
        ``watch_model`` constructor flag.  Use this when you want finer
        control over logging frequency.

        Parameters
        ----------
        model:
            PyTorch model to watch.
        log_freq:
            Logging frequency in steps (default 100).
        """
        if not _WANDB_AVAILABLE or self._run is None:
            return
        try:
            wandb.watch(model, log_freq=log_freq)
        except Exception as exc:
            logger.warning("Failed to watch model: %s", exc)

    # -- helpers ----------------------------------------------------------

    def _ensure_ready(self) -> bool:
        """Check the run is active; return ``False`` if logging is impossible."""
        if not _WANDB_AVAILABLE:
            self._emit_warning()
            return False
        if self._finished or self._run is None:
            logger.debug("W&B run not active — skipping log call")
            return False
        return True

    def _emit_warning(self) -> None:
        """Emit a one-time warning that wandb is not installed."""
        if not self._warning_emitted:
            logger.warning(
                "wandb package is not installed. "
                "Install it with: pip install wandb"
            )
            self._warning_emitted = True

    def _start_gpu_monitor(self) -> None:
        """Start a daemon thread that periodically logs GPU metrics."""
        if not _ensure_nvml():
            logger.debug("pynvml not available — GPU monitoring disabled")
            return

        self._gpu_stop_event.clear()

        def _poll() -> None:
            while not self._gpu_stop_event.wait(self.gpu_poll_interval):
                if self._finished or self._run is None:
                    break
                gpu_metrics = _sample_gpu_usage()
                if gpu_metrics:
                    try:
                        self._run.log(
                            {"system/gpu": gpu_metrics},
                            step=self._step,
                        )
                    except Exception:
                        logger.debug("Failed to log GPU metrics", exc_info=True)

        self._gpu_thread = threading.Thread(target=_poll, daemon=True)
        self._gpu_thread.start()

    def _stop_gpu_monitor(self) -> None:
        """Signal the GPU monitor thread to stop and wait for it."""
        if self._gpu_thread is None:
            return
        self._gpu_stop_event.set()
        self._gpu_thread.join(timeout=5.0)
        self._gpu_thread = None

    @property
    def run_url(self) -> str | None:
        """Public URL of the current W&B run, or ``None``."""
        if self._run is not None and hasattr(self._run, "get_url"):
            try:
                return self._run.get_url()
            except Exception:
                pass
        return None
