global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "distllm-coordinator"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["distllm-coordinator:8000"]

  - job_name: "distllm-nodes"
    metrics_path: "/metrics"
    dns_sd_configs:
      - names:
          - "distllm-worker-headless"
        type: "A"
        port: 9091

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
