global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "distllm-coordinator"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["distllm-coordinator:8000"]

  - job_name: "distllm-nodes"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "distllm-worker-0.distllm-worker:50051"
          - "distllm-worker-1.distllm-worker:50051"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
