apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nodepool-gpu-spot.yaml
  - nodepool-gpu-ondemand.yaml
  - ec2nodeclass-gpu.yaml

commonLabels:
  app.kubernetes.io/name: distributed-llm
  app.kubernetes.io/component: karpenter
