export interface Feature {
  id: string;
  title: string;
  tagline: string;
  bullets: string[];
  code?: { label: string; code: string };
}

export const FEATURES: Feature[] = [
  {
    id: "inference",
    title: "Distributed Inference",
    tagline:
      "Pipeline-parallel serving across consumer GPUs, CPUs, and mixed hardware. Layers split automatically by memory and bandwidth.",
    bullets: [
      "Automatic layer partitioning by device capability",
      "1F1B micro-batched scheduling with straggler detection",
      "PagedAttention KV cache with defragmentation",
      "Speculative decoding with remote draft models",
    ],
    code: {
      label: "Start a 3-node pipeline",
      code: `# Coordinator (laptop with the API)
distllm system api --model meta-llama/Llama-3.1-8B \\
  --host 0.0.0.0 --port 8000

# Workers join with their layer ranges
distllm-node --node-id gpu-box --model meta-llama/Llama-3.1-8B \\
  --start-layer 0 --end-layer 20 --total-layers 32 \\
  --coordinator-host 192.168.1.10`,
    },
  },
  {
    id: "training",
    title: "Distributed Training",
    tagline:
      "Federated LoRA fine-tuning across devices. Gradients stay local, only round-tagged updates are averaged — stale stragglers never corrupt a round.",
    bullets: [
      "Federated LoRA: train adapters, merge on demand",
      "FedProx proximal term with correct local snapshots",
      "Differential privacy: gradient clipping + calibrated noise",
      "Round-versioned gradient aggregation (stale-proof)",
    ],
    code: {
      label: "Federated LoRA round",
      code: `from distllm.core.federated_finetuner import FederatedFineTuner

tuner = FederatedFineTuner(
    node_id="node-1", local_steps=5,
    algorithm="fedlora",
    apply_gradients=apply_fn,
)
tuner.train_round(local_train_fn)`,
    },
  },
  {
    id: "benchmarks",
    title: "Benchmark Suite",
    tagline:
      "Reproducible throughput, latency, and scaling measurements built in — the same numbers we publish, generated by the engine itself.",
    bullets: [
      "Tokens/sec and TTFT per hardware class",
      "Multi-node scaling efficiency curves",
      "Speculative decoding acceptance-rate tracking",
      "SLA latency tiers with compliance percentiles",
    ],
    code: {
      label: "Run the suite",
      code: `python -m pytest tests/benchmark -v

# Or benchmark any endpoint:
python -m distllm.cli.main benchmark \\
  --url http://localhost:8000 \\
  --requests 200 --concurrency 8`,
    },
  },
  {
    id: "deploy",
    title: "One-Command Deploy",
    tagline:
      "Docker, Kubernetes, or bare metal. The CLI generates the compose file or manifest for your exact topology.",
    bullets: [
      "pip install distributed-llm — one package, every role",
      "Docker Compose generator with healthchecks",
      "Kubernetes manifests with GPU scheduling",
      "OpenAI-compatible API from the first minute",
    ],
    code: {
      label: "pip install and serve",
      code: `pip install "distributed-llm[cli,self-hosted]"

distllm system api --model TinyStories-1M \\
  --local --host 0.0.0.0 --port 8000`,
    },
  },
];

export const STATS = [
  { value: "70B", label: "models pooled across consumer GPUs" },
  { value: "4", label: "lines of CLI to a working cluster" },
  { value: "100%", label: "local — your data never leaves your devices" },
  { value: "Apache-2.0", label: "open-source license" },
];

export const FAQ = [
  {
    q: "Do I really need a datacenter GPU?",
    a: "No. DistLLM's partitioner scores every device by memory and bandwidth — a mix of a gaming laptop, a desktop RTX card, and even CPU-only machines can serve a model that none of them could hold alone.",
  },
  {
    q: "How is this different from vLLM or llama.cpp?",
    a: "They are excellent single-node engines. DistLLM is the layer that pools multiple machines into one logical accelerator — and it can drive vLLM as a backend on any node that has a big enough GPU.",
  },
  {
    q: "Does my data leave my devices?",
    a: "No. Inference and training run entirely on your hardware. The only network traffic is between your own nodes over your own LAN.",
  },
  {
    q: "What happens when a node drops mid-request?",
    a: "Health probes detect the failure, the node transitions to OFFLINE, and recovery replays from the last checkpoint. Requests are retried on remaining capacity.",
  },
  {
    q: "Is the API OpenAI-compatible?",
    a: "Yes — /v1/chat/completions, /v1/completions, and /v1/embeddings speak the OpenAI wire format, so existing SDKs and tools work unmodified. Point them at your coordinator and go.",
  },
  {
    q: "What does it cost?",
    a: "The engine is free and open source under Apache-2.0. You pay only the electricity for hardware you already own.",
  },
];
