export const DEPLOY_PLATFORMS = [
  { name: "Docker", desc: "One container per node; compose file generated by the CLI.", href: "/docs/docker/" },
  { name: "Kubernetes", desc: "GPU-scheduled manifests with health probes and autoscaling.", href: "/docs/kubernetes/" },
  { name: "Bare Metal", desc: "pip install and go — coordinator plus workers over SSH.", href: "/docs/installation/" },
  { name: "Hugging Face", desc: "Any hub model loads by name, pinned to a safe revision.", href: "/docs/model-compatibility/" },
];

export const FRAMEWORK_INTEGRATIONS = [
  { name: "LangChain", pkg: "distllm-langchain", note: "ChatDistLLM chat model + DistLLM tool provider for agents." },
  { name: "LlamaIndex", pkg: "distllm-llamaindex", note: "Drop-in LLM class for RAG pipelines and query engines." },
  { name: "CrewAI", pkg: "distllm-crewai", note: "Crew LLM + tool provider so crews run on your own GPUs." },
  { name: "Dify", pkg: "distllm-dify", note: "Provider plugin pointing Dify apps at your cluster." },
  { name: "LiteLLM", desc: "Route through LiteLLM's OpenAI-compatible proxy config." },
  { name: "Open WebUI", desc: "Point Open WebUI at the coordinator URL — it just works." },
  { name: "Ollama-compatible", desc: "Ollama-style endpoints served by the compat module." },
  { name: "OpenAI Agents SDK", desc: "First-class support via the OpenAI wire format." },
  { name: "Semantic Kernel", desc: "Use the OpenAI connector against your cluster." },
];
