"""Chat completion routes: POST /v1/chat/completions."""

import asyncio
import time
from typing import List, Optional, Dict, Union

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field, ConfigDict

from ..api_state import g
from ..streaming import _stream_response
from distllm.core.tool_engine import ToolCallingEngine, ToolCall


router = APIRouter(tags=["chat"])


def _extract_text(content_items) -> str:
    """Extract text from multi-modal content list."""
    if isinstance(content_items, str):
        return content_items
    if isinstance(content_items, list):
        parts = []
        for item in content_items:
            if isinstance(item, dict):
                if item.get("type") == "text":
                    parts.append(item.get("text", ""))
                elif item.get("type") == "image_url":
                    parts.append("[image]")
            elif hasattr(item, "type"):
                if item.type == "text":
                    parts.append(item.text or "")
                elif item.type == "image_url":
                    parts.append("[image]")
        return " ".join(parts)
    return str(content_items)


class ImageURLContent(BaseModel):
    url: str = Field(..., description="Image URL or base64 data URI")
    detail: Optional[str] = Field(default=None, description="Image detail level: 'auto', 'low', 'high'")


class MessageContentItem(BaseModel):
    type: str = Field(..., description="Content type: 'text' or 'image_url'")
    text: Optional[str] = Field(default=None, description="Text content")
    image_url: Optional[ImageURLContent] = Field(default=None, description="Image content")


class ChatMessage(BaseModel):
    role: str = Field(..., description="Role of the message sender", examples=["user", "assistant", "system"])
    content: Optional[Union[str, List[MessageContentItem]]] = Field(
        default=None,
        description="Content of the message. Can be a string or list of text/image_url items.",
        examples=["Hello, how are you?", [{"type": "text", "text": "What's in this image?"}, {"type": "image_url", "image_url": {"url": "https://example.com/image.jpg"}}]],
    )
    name: Optional[str] = Field(default=None, description="Name for function messages or multi-agent scenarios")
    tool_calls: Optional[List[dict]] = Field(default=None, description="Tool calls generated by the assistant")
    tool_call_id: Optional[str] = Field(default=None, description="Tool call ID for tool response messages")
    function_call: Optional[dict] = Field(default=None, description="Deprecated: function call generated by the assistant")


class ChatCompletionRequest(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={
            "examples": [{
                "model": "distributed-llm",
                "messages": [{"role": "user", "content": "Explain distributed inference"}],
                "max_tokens": 256,
                "temperature": 0.7,
                "top_p": 0.9,
                "stream": False,
            }]
        }
    )

    model: str = Field(default="distributed-llm", description="Model identifier")
    messages: List[ChatMessage] = Field(..., description="List of messages in the conversation")
    temperature: float = Field(default=0.7, ge=0, le=2.0, description="Sampling temperature (0-2.0)")
    top_p: float = Field(default=0.9, ge=0, le=1.0, description="Nucleus sampling threshold (0-1)")
    top_k: int = Field(default=0, ge=0, description="Top-k sampling (0 = disabled)")
    max_tokens: int = Field(default=256, ge=1, le=8192, description="Maximum tokens to generate (1-8192)")
    stream: bool = Field(default=False, description="Whether to stream the response")
    stream_options: Optional[dict] = Field(default=None, description="Options for streaming response, e.g. {'include_usage': true}")
    stop: Optional[List[str]] = Field(default=None, description="Stop sequences to halt generation")
    n: int = Field(default=1, ge=1, le=128, description="Number of completions to generate")
    logprobs: Optional[bool] = Field(default=None, description="Whether to return log probabilities")
    top_logprobs: Optional[int] = Field(default=None, ge=0, le=20, description="Number of top logprobs to return")
    presence_penalty: float = Field(default=0.0, ge=-2.0, le=2.0, description="Penalty for new tokens based on presence in text")
    frequency_penalty: float = Field(default=0.0, ge=-2.0, le=2.0, description="Penalty for tokens based on frequency in text")
    seed: Optional[int] = Field(default=None, description="Random seed for deterministic sampling")
    user: Optional[str] = Field(default=None, description="End-user identifier for monitoring and abuse detection")
    logit_bias: Optional[Dict[str, float]] = Field(default=None, description="Modify likelihood of specified tokens")
    response_format: Optional[dict] = Field(default=None, description="Response format constraint, e.g. {'type': 'json_object'}")
    adapter: Optional[str] = Field(default=None, description="LoRA adapter ID to use for this request")
    priority: int = Field(default=2, ge=0, le=3, description="Request priority: 0=critical, 1=high, 2=normal, 3=low")
    tools: Optional[List[dict]] = Field(default=None, description="List of tools the model may call")
    tool_choice: Optional[str] = Field(default=None, description="Controls tool calling: 'none', 'auto', or 'required'")
    functions: Optional[List[dict]] = Field(default=None, description="Deprecated: list of functions for the model to call")
    function_call: Optional[str] = Field(default=None, description="Deprecated: controls function calling behavior")


class ChatChoice(BaseModel):
    index: int = 0
    message: Optional[ChatMessage] = None
    delta: Optional[Dict[str, str]] = None
    finish_reason: Optional[str] = None


class ChatCompletionResponse(BaseModel):
    id: str = Field(default_factory=lambda: f"chatcmpl-{__import__('uuid').uuid4().hex[:12]}")
    object: str = "chat.completion"
    created: int = Field(default_factory=lambda: int(time.time()))
    model: str = "distributed-llm"
    choices: List[ChatChoice]
    usage: Optional[Dict[str, int]] = None
    generation_time: Optional[float] = None


@router.post("/v1/chat/completions")
async def chat_completions(request: Request, body: ChatCompletionRequest):
    """Chat completions endpoint."""
    # Set observability state for middleware
    request.state.model = body.model
    request.state.tenant = body.user or "default"

    coord = g.coordinator
    if coord is None:
        raise HTTPException(status_code=503, detail="No model loaded")

    # Read speculative decoding headers (override config defaults)
    spec_num_tokens = request.headers.get("x-speculative-num-tokens")
    spec_method = request.headers.get("x-speculative-method")
    original_num = None
    original_method = None

    if spec_num_tokens and coord._spec_decoder:
        original_num = coord._spec_decoder.num_assistant_tokens
        coord._spec_decoder.num_assistant_tokens = int(spec_num_tokens)
    if spec_method and coord._spec_decoder:
        original_method = coord._spec_decoder.method
        coord._spec_decoder.method = spec_method

    # Validate requested model against registry
    if hasattr(coord, 'list_models') and body.model not in ("distributed-llm", ""):
        available = coord.list_models()
        if body.model not in available:
            raise HTTPException(
                status_code=400,
                detail=f"Model '{body.model}' not found. Available: {available}"
            )

    # Switch adapter if requested (S-LoRA style: per-request routing)
    request_adapter_id = None
    if body.adapter is not None and hasattr(coord, 'adapter_manager') and coord.adapter_manager is not None:
        request_adapter_id = body.adapter
        # Verify adapter exists
        if body.adapter not in coord.adapter_manager.list_adapters():
            raise HTTPException(
                status_code=400,
                detail=f"Adapter '{body.adapter}' not found. Available: {coord.adapter_manager.list_adapters()}"
            )

    # Check for multi-modal content (images)
    vlm_pipeline = getattr(coord, "_vlm_pipeline", None)
    has_images = vlm_pipeline is not None and any(
        vlm_pipeline.is_multimodal_message([msg.model_dump()])
        for msg in body.messages
    )

    if has_images:
        # Multi-modal: parse messages, encode images, build prompt with image tokens
        vlm_messages = [msg.model_dump() for msg in body.messages]
        text_prompt, images = vlm_pipeline.parse_messages(vlm_messages)
        image_embeddings = vlm_pipeline.encode_images_to_embeddings(images)
        prompt, _ = vlm_pipeline.build_prompt_with_images(text_prompt, image_embeddings)
    else:
        # Text-only: simple role:content formatting
        prompt = "\n".join([
            f"{msg.role}: {msg.content}" if isinstance(msg.content, str) else f"{msg.role}: {_extract_text(msg.content)}"
            for msg in body.messages
        ])

    # Tool calling setup
    tool_engine = ToolCallingEngine()
    tool_calls_list = []
    tool_choice_value = body.tool_choice

    # Parse tools if provided
    tool_schemas = []
    if body.tools:
        tool_schemas = tool_engine.parse_schemas(body.tools)

    # Handle deprecated functions parameter
    if body.functions and not body.tools:
        func_tools = []
        for func_def in body.functions:
            func_tools.append({
                "type": "function",
                "function": func_def,
            })
        tool_schemas = tool_engine.parse_schemas(func_tools)
        if body.function_call:
            tool_choice_value = body.function_call

    # Build tool-augmented prompt if tools are provided
    if tool_schemas and not body.stream:
        prompt, _ = tool_engine.build_tool_prompt(
            tool_schemas,
            [m.model_dump(exclude_none=True) for m in body.messages],
            tool_choice=tool_choice_value,
        )

    # Build schema constraint for structured output
    schema = None
    if body.response_format:
        fmt_type = body.response_format.get("type", "")
        if fmt_type == "json_object":
            schema = {}  # Simple JSON constraint
        elif fmt_type == "json_schema" and "schema" in body.response_format:
            schema = body.response_format["schema"]

    if body.stream:
        return StreamingResponse(
            _stream_response(prompt, body, "chat.completion.chunk", "chatcmpl-"),
            media_type="text/event-stream",
        )

    start_time = time.time()

    try:
        # Use batch scheduler if available
        if coord.scheduler is not None:
            request_id = coord.generate_async(
                prompt,
                max_new_tokens=body.max_tokens,
                temperature=body.temperature,
                top_p=body.top_p,
                schema=schema,
                priority=body.priority,
                adapter_id=request_adapter_id,
            )
            result = await asyncio.to_thread(coord.wait_for_result, request_id)
        else:
            result = await asyncio.to_thread(
                coord.generate,
                prompt,
                body.max_tokens,
                body.temperature,
                body.top_p,
            )

        elapsed = time.time() - start_time

        generated = result[len(prompt):] if result.startswith(prompt) else result

        # Check for tool calls in generated text
        finish_reason = "stop"
        assistant_tool_calls = None
        messages_list = [m.model_dump(exclude_none=True) for m in body.messages]

        if tool_schemas and tool_engine.has_tool_calls(result):
            # Extract tool calls
            tool_calls_list = tool_engine.extract_tool_calls(result)

            # Enforce tool_choice constraint
            tool_calls_list = tool_engine.enforce_tool_choice(tool_choice_value, tool_calls_list)

            if tool_calls_list:
                # Execute tool calls
                tool_results = tool_engine.execute_tool_calls(tool_calls_list)

                # Build tool_call response
                assistant_tool_calls = [tc.to_openai_dict() for tc in tool_calls_list]

                # If we have results, continue generation with injected results
                if tool_results and tool_engine.should_continue_after_tool_calls(tool_calls_list, tool_results):
                    # Inject tool results into conversation
                    new_messages = tool_engine.inject_tool_results(
                        messages_list,
                        result,
                        tool_calls_list,
                        tool_results,
                    )

                    # Build new prompt and generate final response
                    final_prompt, _ = tool_engine.build_tool_prompt(
                        tool_schemas,
                        new_messages,
                        tool_choice="none",  # Don't call tools again
                    )

                    # Second generation pass with tool results
                    if coord.scheduler is not None:
                        final_result = await asyncio.to_thread(
                            coord.generate,
                            final_prompt,
                            body.max_tokens,
                            body.temperature,
                            body.top_p,
                        )
                    else:
                        final_result = await asyncio.to_thread(
                            coord.generate,
                            final_prompt,
                            body.max_tokens,
                            body.temperature,
                            body.top_p,
                        )

                    # Extract the continuation after tool results
                    generated = final_result[len(final_prompt):] if final_result.startswith(final_prompt) else final_result
                    finish_reason = "tool_calls"

        # Compute token counts without re-encoding (prompt already tokenized in generate())
        prompt_tokens = len(coord.tokenizer.encode(prompt))
        completion_tokens = len(coord.tokenizer.encode(generated))

        # Build response message
        response_message = {"role": "assistant"}
        if assistant_tool_calls:
            response_message["tool_calls"] = assistant_tool_calls
            response_message["content"] = None  # Tool calls replace content
        else:
            response_message["content"] = generated.strip()

        return ChatCompletionResponse(
            model=body.model,
            choices=[
                ChatChoice(
                    message=ChatMessage(**response_message),
                    finish_reason=finish_reason,
                )
            ],
            usage={
                "prompt_tokens": prompt_tokens,
                "completion_tokens": completion_tokens,
                "total_tokens": prompt_tokens + completion_tokens,
            },
            generation_time=round(elapsed, 3),
        )
    finally:
        # Restore original speculative settings
        if spec_num_tokens and coord._spec_decoder:
            coord._spec_decoder.num_assistant_tokens = original_num
        if spec_method and coord._spec_decoder:
            coord._spec_decoder.method = original_method
