apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
spec:
  template:
    spec:
      containers:
        - name: coordinator
          env:
            - name: DISTLLM_LOG_LEVEL
              value: debug
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 2
              memory: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  template:
    spec:
      containers:
        - name: worker
          env:
            - name: DISTLLM_LOG_LEVEL
              value: debug
          resources:
            requests:
              cpu: 1
              memory: 4Gi
            limits:
              cpu: 4
              memory: 16Gi
