apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: distllm-worker
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: worker
          resources:
            requests:
              cpu: 1
              memory: 4Gi
            limits:
              cpu: 4
              memory: 16Gi
