apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: distllm
  labels:
    app: distllm
spec:
  selector:
    matchLabels:
      app: distllm
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
