"""Standardized error hierarchy for distributed LLM."""

from distllm.errors.types import (
    DistLLMError,
    NodeError,
    NodeUnreachableError,
    CircuitBreakerError,
    GatewayError,
    ProviderTimeoutError,
    CommunicationError,
    SerializationError,
    GRPCTimeoutError,
    ProtoError,
    ModelError,
    ModelNotFoundError,
    ModelLoadError,
    OOMError,
    ConfigError,
    ConfigValidationError,
    BatchError,
    BatchCapacityError,
    ConstraintError,
    ConstraintViolationError,
    InputValidationError,
)
from distllm.errors.retry import RetryPolicy, with_retry, with_retry_async
from distllm.errors.policies import (
    ERROR_RETRY_POLICIES,
    get_retry_policy,
    should_retry,
    get_retry_delay,
)

__all__ = [
    "DistLLMError",
    "NodeError",
    "NodeUnreachableError",
    "CircuitBreakerError",
    "GatewayError",
    "ProviderTimeoutError",
    "CommunicationError",
    "SerializationError",
    "GRPCTimeoutError",
    "ProtoError",
    "ModelError",
    "ModelNotFoundError",
    "ModelLoadError",
    "OOMError",
    "ConfigError",
    "ConfigValidationError",
    "BatchError",
    "BatchCapacityError",
    "ConstraintError",
    "ConstraintViolationError",
    "InputValidationError",
    "RetryPolicy",
    "with_retry",
    "with_retry_async",
    "ERROR_RETRY_POLICIES",
    "get_retry_policy",
    "should_retry",
    "get_retry_delay",
]
