apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: distllm-worker
spec:
  replicas: 4
  template:
    spec:
      containers:
        - name: worker
          resources:
            requests:
              cpu: 4
              memory: 16Gi
              nvidia.com/gpu: 1
            limits:
              cpu: 8
              memory: 32Gi
              nvidia.com/gpu: 1
